### ISSUE TITLE
edge module not pre-compiled for node.js v12.4.0

### ISSUE THREAD

**Issue by manuargue** [mike-eason/oledb#4]
I'm trying to use this `oledb` package from an Electron 6.0.x application that uses Node.js v12.4.0.
The test code, based on the package sample, is:
```
  const oledb = require('oledb');
  const connectionString = 'Provider=SQLOLEDB;Data Source=(local)\\SQLEXPRESS;Initial Catalog=test;Persist Security Info=True;User Instance=False;User ID=sa;Password=1234;';
  const command = 'select * from TestTable;';
  const db = oledb.oledbConnection(connectionString);
  db.query(command)
  .then(result => {
    console.log(result);
  },
  err => {
    console.error(err);
  });
```
When starting the Electron application, the following error occurs:
![image](https://user-images.githubusercontent.com/511857/64627875-fcfe1f80-d422-11e9-8d1f-7d612fff8287.png)

Is there a way I can use [electron-edge-js ](https://www.npmjs.com/package/electron-edge-js) instead edge-js package? electron-edge-js is built against the node.js versions distributed along with Electron releases.

**Comment by mike-eason** [comment]
Hello.

Please try using the `oledb-electron` package which is a branch of this project: https://www.npmjs.com/package/oledb-electron

I have updated the branch from `master` so it should be up to date.

**Comment by manuargue** [comment]
Thanks! I haven’t seen that. I’ll close this issue
